version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - zipkin
    command: go run cmd/main.go cmd/wire_gen.go
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
