FROM golang:latest as builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o cep-input cmd/main.go cmd/wire_gen.go

FROM scratch
COPY --from=builder /app/cmd/.env ./app/cmd/.env
COPY --from=builder /app/cep-input .
ENTRYPOINT ["./cep-input"] 
