// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"pos-graduacao/desafios/observabilidade/input/internal/infra/forecast"
	"pos-graduacao/desafios/observabilidade/input/internal/infra/forecast/weather"
	"pos-graduacao/desafios/observabilidade/input/internal/usecase"
	"pos-graduacao/desafios/observabilidade/input/internal/web/handler"
)

// Injectors from wire.go:

func provideGetForecastUC() usecase.GetForecast {
	weatherApi := weather.NewWeatherApi()
	getForecast := usecase.NewGetForecastUseCase(weatherApi)
	return getForecast
}

func NewCepForecastHandler() handler.GetCepForecastHandler {
	getForecast := provideGetForecastUC()
	getCepForecastHandler := handler.NewCepForecastHandler(getForecast)
	return getCepForecastHandler
}

// wire.go:

var setForecastProviderInterface = wire.NewSet(weather.NewWeatherApi, wire.Bind(new(forecast.ForecastProviderInterface), new(*weather.WeatherApi)))
